In [1]:
import numpy as np
np.random.seed(1)

In [5]:
# step 1: create data set

mu_vec1=np.array([0,0,0]) # sample mean
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]]) #sample covariance

class1_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20).T # 3X20 matrix
print(class1_sample)

[[ 1.62434536 -1.07296862  1.74481176 -0.24937038 -0.3224172  -1.09989127
   0.04221375  1.14472371  0.90085595 -0.93576943 -0.69166075 -0.84520564
  -1.11731035  0.74204416 -0.74715829 -0.63699565  0.12015895 -0.35224985
  -0.20889423  0.93110208]
 [-0.61175641  0.86540763 -0.7612069   1.46210794 -0.38405435 -0.17242821
   0.58281521  0.90159072 -0.68372786 -0.26788808 -0.39675353 -0.67124613
   0.2344157  -0.19183555  1.6924546   0.19091548  0.61720311 -1.1425182
   0.58662319  0.28558733]
 [-0.52817175 -2.3015387   0.3190391  -2.06014071  1.13376944 -0.87785842
  -1.10061918  0.50249434 -0.12289023  0.53035547 -0.6871727  -0.0126646
   1.65980218 -0.88762896  0.05080775  2.10025514  0.30017032 -0.34934272
   0.83898341  0.88514116]]


In [6]:
mu_vec2=np.array([1,1,1]) # sample mean
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]]) #sample covariance

class2_sample=np.random.multivariate_normal(mu_vec2,cov_mat2,20).T # 3X20 matrix
print(class2_sample)

[[ 0.24560206  0.70190716  2.13162939 -0.39649634  1.16003707 -1.02220122
   1.23009474  0.79924193  1.19829972  1.37756379  2.19891788  0.36126959
   0.65614632  1.69803203  1.40349164  1.16938243  0.73378149  1.31515939
   1.35054598 -0.61577235]
 [ 2.25286816  1.48851815  2.51981682 -0.44411381  1.87616892  0.69379599
   1.76201118  1.18656139  1.11900865  1.12182127  1.18515642  1.42349435
   1.04359686  0.55287144  1.59357852  1.74055645  1.03261455  1.84616065
  -0.31228341  2.12141771]
 [ 1.51292982  0.92442829  3.18557541  0.49553414  1.31563495  1.82797464
   0.77767186  1.41005165  0.32933771  2.12948391  0.62471505  1.07734007
   0.37999916  2.2245077  -0.09491185  0.0462994  -0.37311732  0.14048406
   0.96130449  1.40890054]]


In [12]:
# setp 2 : plot the data
%pylab inline
from matplotlib import pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [13]:
# #figure, width and height
# fig =plt.figure(figsize=(8,8))
# #3d subplot
# #these are subplot grid parameters encoded as asingle integer, 1x1 grid, 1st subplot
# ax=fig.add_subplot(111,projection='3d')
# #fontsize
# plt.rcParams['legend.fontsize']=10

# #plot samples
# ax.plot(class1_sample[0,:],class1_sample[1,:],class1_sample[2,:],'o',
#        markersize=8,color='blue',alpha=0.5,label='class1')
# ax.plot(class2_sample[0,:],class2_sample[1,:],class2_sample[2,:],'^',
#        markersize=8,color='green',alpha=0.5,label='class2')

# ax.legend(loc='upper right')

# plt.show()

ValueError: Unknown projection '3d'

In [26]:
# step 3 : merg e the data into one big ass dataset

all_samples=np.concatenate((class1_sample,class2_sample), axis=1)
all_samples.T

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842],
       [ 0.04221375,  0.58281521, -1.10061918],
       [ 1.14472371,  0.90159072,  0.50249434],
       [ 0.90085595, -0.68372786, -0.12289023],
       [-0.93576943, -0.26788808,  0.53035547],
       [-0.69166075, -0.39675353, -0.6871727 ],
       [-0.84520564, -0.67124613, -0.0126646 ],
       [-1.11731035,  0.2344157 ,  1.65980218],
       [ 0.74204416, -0.19183555, -0.88762896],
       [-0.74715829,  1.6924546 ,  0.05080775],
       [-0.63699565,  0.19091548,  2.10025514],
       [ 0.12015895,  0.61720311,  0.30017032],
       [-0.35224985, -1.1425182 , -0.34934272],
       [-0.20889423,  0.58662319,  0.83898341],
       [ 0.93110208,  0.28558733,  0.88514116],
       [ 0.24560206,  2.25286816,  1.512

In [27]:
# step 4 : compute the dimensional mean vector, it will help compute the covariance matrix
# mean for each feature
mean_x=np.mean(all_samples[0,:])
mean_y=np.mean(all_samples[1,:])
mean_z=np.mean(all_samples[2,:])

#3d mean vector
mean_vector=np.array(([[mean_x],[mean_y],[mean_z]]))
print(mean_vector)


[[ 0.41667492]
 [ 0.69848315]
 [ 0.49242335]]


In [29]:
# step 5 : compute covaricance matrix
cov_mat=np.zeros((3,3))

for i in range((all_samples.shape[1])):
    cov_mat+=(all_samples[:,i].reshape(3,1)-mean_vector).dot((all_samples[:,i].reshape(3,1)-mean_vector).T)
print('Covariance Matix:\n', cov_mat)    

Covariance Matix:
 [[ 38.4878051   10.50787213  11.13746016]
 [ 10.50787213  36.23651274  11.96598642]
 [ 11.13746016  11.96598642  49.73596619]]


In [31]:
# step 6 : compute eigenvectors & eigenvalues
eig_val, eig_vec = np.linalg.eig(cov_mat)
print(eig_val)
print(eig_vec)

[ 65.16936779  32.69471296  26.59620328]
[[-0.49210223 -0.64670286  0.58276136]
 [-0.47927902 -0.35756937 -0.8015209 ]
 [-0.72672348  0.67373552  0.13399043]]


In [32]:
# step 7 : crerate eigenpair from both and sort them
eig_pairs=[(np.abs(eig_val[i]),eig_vec[:,i]) for i in range(len(eig_val))]
#sor the (eigenvalue,eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# visually confirm that the list is correctly sorted by decressing eigenvalues
for i in eig_pairs:
    print(i[0])

65.1693677908
32.6947129632
26.5962032821


In [33]:
# step 8 : choose k eigvectors

matrix_w=np.hstack((eig_pairs[0][1].reshape(3,1), eig_pairs[1][1].reshape(3,1)))
print('Matrix W:\n',matrix_w)

Matrix W:
 [[-0.49210223 -0.64670286]
 [-0.47927902 -0.35756937]
 [-0.72672348  0.67373552]]


In [36]:
# step 9: transform our data using this eigenpair
transformed=matrix_w.T.dot(all_samples)
print(transformed.shape)

(2, 40)


### compare PCA T-SNE LDA
### 3 most popular dimension reduce techniques
- PCA: best generic DR method (generally for unsupervised)
- LDA(linear dicriminant analyses): best supervised data, sames as PCA except we compute mean vectors for each of the classes
- T-SNE: best visulization
- - step 1: compute similarity matrix between all feature vectors
- - step 2: compute similarity matrix from map points
- - step 3: use gradient descent to minimimze distance between matrices